const buf1 = Buffer.alloc(10);
const buf2 = Buffer.from('hello buffer')
const buf3 = Buffer.from([98, 2, 3])
console.log(buf1.toJSON())
console.log(buf2.toJSON())
console.log(buf3.toJSON())
console.log(buf1.length)
console.log(buf2.length)
buf1.write('buffer is good')
console.log(buf1)
console.log(buf1.toJSON())